import os

BASE_DIR = "."

PROJECT_FOLDERS = [
    "0-Beginner-Projects",
    "1-Intermediate-Projects",
    "2-Advanced-Projects",
    "3-Expert-Projects",
    "4-AI-Security",
    "5-Cloud-Security",
    "6-RedTeam",
    "7-BlueTeam",
    "8-OSINT",
    "9-Linux-Automation"
]

# ============================
# LOAD TITLES FROM FILES
# ============================
def load_titles(file_path, count):
    with open(file_path, "r") as f:
        titles = [line.strip() for line in f.readlines()]
    if len(titles) != count:
        raise ValueError(f"{file_path} must have exactly {count} lines!")
    return titles

project_titles = load_titles("project_titles.txt", 1000)
thm_titles = load_titles("thm_titles.txt", 200)

# ============================
# README TEMPLATES
# ============================

PROJECT_TEMPLATE = """# Project-{num} — {title}

## 📌 Description
{title} — autogenerated project for Devansh 365 Journey.

## 🎯 Skills Practiced
- Security
- Automation
- Programming

## 📝 Notes
(Add notes)

---
"""

THM_TEMPLATE = """# THM-{num} — {title}

## 📌 Description
Write-up for TryHackMe room: {title}

## 🛠 Skills Practiced
- Enumeration
- PrivEsc
- Exploitation

## 📝 Notes
(Add notes)
"""

# ============================
# GENERATE PROJECT FOLDERS
# ============================

def generate_projects():
    print("📁 Creating 1000 project folders + README...")

    index = 0
    for category in PROJECT_FOLDERS:
        os.makedirs(category, exist_ok=True)

        for i in range(100):
            num = f"{index+1:04d}"
            title = project_titles[index]

            folder = os.path.join(category, f"Project-{num}")
            os.makedirs(folder, exist_ok=True)

            with open(os.path.join(folder, "README.md"), "w") as f:
                f.write(PROJECT_TEMPLATE.format(num=num, title=title))

            index += 1

    print("✅ All 1000 project folders generated!")


# ============================
# GENERATE THM LABS
# ============================

def generate_thm():
    print("📁 Creating 200 TryHackMe labs...")

    base = "TryHackMe-Labs"
    os.makedirs(base, exist_ok=True)

    for i in range(200):
        num = f"{i+1:03d}"
        title = thm_titles[i]

        folder = os.path.join(base, f"THM-{num}")
        os.makedirs(folder, exist_ok=True)

        with open(os.path.join(folder, "README.md"), "w") as f:
            f.write(THM_TEMPLATE.format(num=num, title=title))

    print("🔥 All 200 THM labs generated!")


# ============================
# MAIN
# ============================

generate_projects()
generate_thm()

print("\n🎉 ALL DONE! 1000 PROJECTS + 200 THM LABS CREATED WITH TITLES.\n")